# Generated by Django 3.0.5 on 2020-05-26 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devspot', '0002_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='pimages'),
        ),
    ]
