# Generated by Django 3.0.5 on 2020-05-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devspot', '0004_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('about', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='aimages')),
            ],
        ),
    ]
